version: 2

jobs:
  build:
    branches:
      only:
        - circleci
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/coin
    steps:
      - checkout
      - run:
          name: Installing boost, CMake and Mercurial packages
          command: |
            brew install boost
            brew install cmake
            brew install mercurial
      - run:
          name: configuring, building and installing
          command: |
            mkdir installed
            cmake -H. -Bbuildit -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCOIN_BUILD_DOCUMENTATION=OFF -DCMAKE_INSTALL_PREFIX=/Library/Frameworks -DCOIN_BUILD_SINGLE_LIB=ON -DCOIN_BUILD_MAC_FRAMEWORK=ON
            cmake --build buildit --target install --config Release -- -j 4
